# 编译的名称
name: 自动部署okteto


# 设置触发条件
on:
  # 仓库触发工作流
  #repository_dispatch:
  # 编辑文件触发开始编译
  push:
  # 手动触发工作流
  workflow_dispatch:
    inputs:
      build:
        description: 'build-huginn'
        required: true
        default: '自动部署okteto'
  # 定时触发编译(每天早5点)
  schedule:
     - cron: '0 22 * * *'
  # 点☆Star触发开始编译
  watch:  
     types: [started]
     
# 任务集
jobs:
  build:
    # 选择虚拟环境
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    # 运行步骤
    steps:
    
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y upgrade
        sudo apt-get -y install wget
        sudo apt-get -y install curl
    - name: Clone source
      run: |
        cd /home/runner
        wget https://github.com/okteto/okteto/releases/download/1.12.15/okteto-Linux-x86_64
        chmod +x ./okteto-Linux-x86_64
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
    - name: go kaishi
      run: |
        #kubectl 重启pod
        /home/runner/okteto-Linux-x86_64 login --token ${{ secrets.OKTETO_TOKEN }}
        #okteto的api密钥
        /home/runner/okteto-Linux-x86_64 namespace blog-hzcy
        kubectl get pod -l app=my-huginn -n blog-hzcy -o yaml | kubectl replace --force -f -
        kubectl get pod -l app=my-huginn-web -n blog-hzcy -o yaml | kubectl replace --force -f -
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: /usr/local/bin/kubectl
